### ISSUE TITLE
The reason why Self-Attentions are not inflated?

### ISSUE THREAD

**Issue by Ground-A-Video** [showlab/Show-1#12]
As far as I know, pioneered by Tune-A-Video, it has been a very standard technique to inflate Self-Attention layers on temporal axis (i.e., concatenating key and values computed from other frames' latent features), such as SparseCausal Attentions... and also many other attentions from different papers.

This practice is very effective in attaining global semantic consistency in the generated videos.
Is there a reason why Show-1 remain self-attention layers intact?

Personally, I experienced the quality and definition of the generated videos are degraded when using this kind of Spatial Self Attn inflation. Is this the reason why?

Thank you!

**Comment by junhaozhang98** [comment]
Thanks for your queation! If you leverage the T2I model for video editing without video training, SparseCausal Attentions is very important for perserving temporal consistency. If you train the model using with massive video data, the self-attention is good enough as temporal consistency is ensured by temporal conv and attention layers.
