### ISSUE TITLE
Hellow where wis the model? 

### ISSUE THREAD

**Issue by spacewalkingninja** [showlab/Show-1#2]
Please the open source community neads this model wreally weally faASAPSstygd,hnjsfb a PLEASE WE BEG YOU AND WE BOW; WE ARE ON OUR KNEEES; YOUU MUST RELEASE THE MODEL!!! PLEASE PLEASE PLEASE#EW"!"!"!"!"!"!"!"!"!"!"!"!"!"! AAAAAAAAAAAAAAAAAAAAA REALLY NEEDED!!!!!! 
Please gyus we nedewmnrfs the model please this is verty important cvforu us to use this model is very pomkrtatn

**Comment by junhaozhang98** [comment]
Code and weight has been released.
