### ISSUE TITLE
Error Loading

### ISSUE THREAD

**Issue by Absinthze** [showlab/Show-1#25]
I'm probably not setting up the correct environment, but I'm getting this error in Windows 10.   

C:\Show-1>python run_inference.py
Traceback (most recent call last):
  File "C:\Show-1\run_inference.py", line 5, in <module>
    import torch
  File "C:\Users\MRH\anaconda3\lib\site-packages\torch\__init__.py", line 122, in <module>
    raise err
OSError: [WinError 127] The specified procedure could not be found. Error loading "C:\Users\MRH\anaconda3\lib\site-packages\torch\lib\nvfuser_codegen.dll" or one of its dependencies.

**Comment by junhaozhang98** [comment]
This code is tested on Linux server, which is recommended.
